FMFWebApp/BootstrapWebApplication/ViewModels/ShipViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BootstrapWebApplication.Models
{
    public class ShipViewModel : ViewModelBaseWithChangeEvent
    {
        public int Id { get; set; }

        public string Code { get; set; }

        public string ShipType { get; set; }

        public string Status { get; set; }

        public string Name { get; set; }

        public int? ShippingCompanyId { get; set; }

        public string ShippingCompanyName { get; set; }

        public string Description { get; set; }
    }
}

FMFWebApp/BootstrapWebApplication/Controllers/LogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BootstrapWebApplication.Models;
using BootstrapWebApplication.DAL;
using BootstrapWebApplication.BLL;
using AutoMapper;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;


namespace BootstrapWebApplication.Controllers
{
    public class LogController : Controller<ChangeEventItem>
    {
        protected override IQueryable<ChangeEventItem> PagedListFilter(IQueryable<ChangeEventItem> list, string filterName = null)
        {
            return null;
            //return list.Where(s => s.Id.ToString().ToUpper().Contains(filterName.ToUpper())
            //                    || s.Description.ToString().ToUpper().Contains(filterName.ToUpper()) 
            //                    || s.Code.ToString().ToUpper().Contains(filterName.ToUpper()));
        }

        protected override void AddViewBag(ChangeEventItem ChangeEventItem)
        {
            //ViewBag.ChangeEventItemId = new SelectList(db.ChangeEventItems.ToList().Select(m => new SelectListItem
            //{
            //    Text = m.Bank.Name,
            //    Value = m.Id.ToString()
            //}), "Value", "Text", ChangeEventItem != null ? ChangeEventItem.Id : 0);
        }

        protected override DataSourceResult Get(int id, DataSourceRequest request)
        {
            // Avoid the circular reference by creating a View Model object and skiping the Customer property
            var result = db.ChangeEventItems.Where(x => x.EntityId == id).Select(m => new LogViewModel()
            {
                Id = m.Id,
                Date = m.Date,
                Type = m.Type,
                UserIdCode = m.UserIdCode,
                //ChangeEvent = m.ChangeEvent,
                TableName = m.TableName,
                ColumnName = m.ColumnName,
                ChangedFrom = m.ChangedFrom,
                ChangedTo = m.ChangedTo,
                ChangeEventId = m.ChangeEvent != null ? m.ChangeEvent.Id : -1
            });
            return result.OrderBy(x => x.Date).ToDataSourceResult(request);
        }

        public ActionResult Logs(int? id)
        {
            return GetRelatedDataForParent<Entity>(id, "Logs");
        }
    }
}

FMFWebApp/BootstrapWebApplication/Controllers/TripController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BootstrapWebApplication.DAL;
using BootstrapWebApplication.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using AutoMapper;
using BootstrapWebApplication.BLL;
using BootstrapWebApplication.Hubs;
using Microsoft.AspNet.SignalR;

namespace BootstrapWebApplication.Controllers
{
    public class TripController : Controller<Trip>
    {
        protected override Trip DetailsGetHook(Trip obj)
        {
            // load tripdeductions explicitly
            db.Entry(obj).Collection(x => x.TripLines).Load();
            db.Entry(obj).Collection(x => x.TripDeductions).Load();
            db.Entry(obj).Collection(x => x.SignOns).Load();
            return base.DetailsGetHook(obj);
        }

        protected override DataSourceResult Get(int id, DataSourceRequest request)
        {
            // Avoid the circular reference by creating a View Model object and skiping the Customer property
            var ship = db.Ships.Where(x => x.Id == id).FirstOrDefault();// db.Set<Ship>().Find(id);
            if (ship != null)
            {
                //var result = ship.Trips.Select(m => Mapper.CreateMap<Trip, ShipTripViewModel>());
                var user = GetUser();
                var laborInsuranceAmountPerDay = (user != null && user.AppSettings != null) ? user.AppSettings.LaborInsuranceAmountPerDay : 0m;


                var fromDate = new DateTime(DateTime.Now.Year-1, 1, 1);// DateTime.Now.AddYears(-1);
                var toDate = new DateTime(DateTime.Now.Year + 1, 1, 1); // Hans legg 1 ár fram
                
                if (request.Filters.Count == 1)
                {
                    var filter = request.Filters[0] as Kendo.Mvc.CompositeFilterDescriptor;
                    if (filter.FilterDescriptors.Count == 2)
                    {
                        var filter1 = filter.FilterDescriptors[0] as Kendo.Mvc.FilterDescriptor;
                        var filter2 = filter.FilterDescriptors[1] as Kendo.Mvc.FilterDescriptor;
                        if (filter1.Member == "from")
                        {
                            DateTime.TryParseExact(filter1.Value as string, Core.Settings.Instance.DateTimeFormatReporting, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out fromDate);
                        }
                        if (filter2.Member == "to")
                        {
                            DateTime.TryParseExact(filter2.Value as string, Core.Settings.Instance.DateTimeFormatReporting, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out toDate);
                        }
                    }
                }
                request.Filters.Clear();
                
              //  var tripsOrdered = GetShipTripsOrdered(ship);//, fromDate, toDate);
                var tripsOrdered = ship.Trips
                    .FilterDeleted()
                    .Where(x => DateTime.Compare(fromDate, x.From.Value) <= 0 && DateTime.Compare(toDate, x.To.Value) >= 0) //Hans
                    .OrderByDescending(x => x.From)
                    //.ThenByDescending(x => x.From)
                    .AsQueryable();
                

                //var result = new List<ShipTripViewModel>();
                //foreach (var trip in tripsOrdered)
                //{
                //    db.Entry(trip).Collection(x => x.SignOns).Load();
                //    result.Add(new ShipTripViewModel()
                //    {
                //        Id = trip.Id,
                //        TripId = trip.TripId,
                //        From = trip.From,
                //        To = trip.To,
                //        Days = trip.Days,
                //        LaborInsurance = trip.LaborInsurance,
                //        LaborInsuranceTotal = trip.LaborInsurance.HasValue ? new Nullable<decimal>(trip.LaborInsurance.Value * (decimal)trip.Days) : null,
                //        // todo: how's this calculated?
                //        Paid = null,
                //        Document = "?",
                //        Crew = trip.Crew,
                //        CrewIncludingStayingAtHome = trip.CrewIncludingStayingAtHome,
                //        CrewWithInsurance = trip.CrewWithInsurance,
                //        CrewSharePercentage = trip.CrewSharePercentage,
                //        CrewSharePart = trip.CrewSharePart,
                //        VIDAR = trip.VIDAR,
                //        CrewSharePerCrewMember = trip.MANN_PART,//m.CrewSharePerCrewMember,<-- requires explicit loading of TripLines + TripDeductions (costly). Use mann_part
                //        TotalWeight = trip.TotalWeight,// m.TotalWeightCalculated,// m.TotalWeight,
                //        //todo: til per dg
                //    });
                //}

                var result = tripsOrdered.Select(m => new ShipTripViewModel()
                {
                    Id = m.Id,
                    TripId = m.TripId,
                    TripIdStr = ("" + m.TripId).PadLeft(4).Replace(" ", "0"),
                    From = m.From,
                    To = m.To,
                    Days = m.Days,
                    LaborInsurance = m.LaborInsurance,
                    LaborInsuranceTotal = m.LaborInsuranceTotal,
                    // todo: how's this calculated?
                    //Paid = null,
                    Document = "?",
                    Crew = m.Crew,
                    CrewIncludingStayingAtHome = m.CrewIncludingStayingAtHome,
                    CrewWithInsurance = m.CrewWithInsurance,
                    CrewSharePercentage = m.CrewSharePercentage,
                    CrewSharePart = m.CrewSharePart,
                    VIDAR = m.VIDAR,
                    CrewSharePerCrewMember = m.MANN_PART,//m.CrewSharePerCrewMember,<-- requires explicit loading of TripLines + TripDeductions (costly). Use mann_part
                    TotalWeight = m.TotalWeight,// m.TotalWeightCalculated,// m.TotalWeight,
                    TRYG_BILAG = m.TRYG_BILAG,
                    TRYG_KRHB = m.TRYG_KRHB,
                    TRYG_KRHB_TOTAL = m.LundinAlkaPaymentBookings.Where(x => x.ChangeEvent != null && !x.ChangeEvent.DeletedOn.HasValue).Sum(x => x.Amount),
                    LaborInsuranceDifference = m.TRYG_KRHB.HasValue ? m.LaborInsuranceTotal - m.TRYG_KRHB : 0m,
                    MembershipPayment = m.SignOns.FilterDeleted().Sum(x => (x.HasInsurance && x.KR_IALT.HasValue) ? (x.KR_IALT.Value * 0.0125m) : 0m),
                    MembershipPaymentPaid = m.MembershipPaymentPaid.HasValue ? m.MembershipPaymentPaid.Value : 0m,
//               MembershipPaymentTotal = m.LundinMembershipPaymentBookings.Where(x => x.ChangeEvent != null && !x.ChangeEvent.DeletedOn.HasValue).Last().Amount, // Hans vís síðsta gjald
//               MembershipPaymentTotal = m.LundinMembershipPaymentBookings.Where(x => x.ChangeEvent != null && !x.ChangeEvent.DeletedOn.HasValue).Sum(x => x.Amount), // Hans vís sum av gjøldum
                    MembershipPaymentNr = m.MembershipPaymentNr, // last(m.LundinMembershipPaymentBookings.Where(x => x.ChangeEvent != null && !x.ChangeEvent.DeletedOn.HasValue).bokid),  // Hans vís síðsta gjald
                    //todo: til per dg
                });
                return result.ToDataSourceResult(request);
            }
            return null;
        }

        protected override IQueryable<Trip> PagedListFilter(IQueryable<Trip> list, string filterName = null)
        {
            return list.Where(s => s.Id.ToString().ToUpper().Contains(filterName.ToUpper())
                                   || s.From.ToString().ToUpper().Contains(filterName.ToUpper())
                                   || s.To.ToString().ToUpper().Contains(filterName.ToUpper())
                                   );
        }

        protected override void AddViewBag(Trip trip)
        {
            ViewBag.CompanyId = new SelectList(db.Companies.ToList().Select(m => new SelectListItem
            {
                Text = m.Name + " (" + m.Code + ")",
                Value = m.Id.ToString()
            }), "Value", "Text", trip != null ? trip.TripLines.FirstOrDefault().CompanyId : null);

            ViewBag.DeductionTypeId = new SelectList(db.DeductionTypes.ToList().Select(m => new SelectListItem
            {
                Text = m.Name + " (" + m.Code + ")",
                Value = m.Id.ToString()
            }), "Value", "Text", trip != null ? trip.TripDeductions.FirstOrDefault().DeductionTypeId : null);

            ViewBag.PortOfLandingId = new SelectList(db.Companies.ToList().Select(m => new SelectListItem
            {
                Text = m.Name,
                Value = m.Id.ToString()
            }), "Value", "Text");
            //ViewBag.ChangeEventId = new SelectList(db.ChangeEvents, "Id", "CreatedByUserIdCode");
            //ViewBag.PostalId = new SelectList(db.Postals, "Id", "CityName");
            //ViewBag.ShipId = new SelectList(db.Ships, "Id", "Code");
            //ViewBag.ShippingCompanyId = new SelectList(db.ShippingCompanies, "Id", "Name");
            //ViewBag.ShipTypeId = new SelectList(db.ShipTypes, "Id", "TEKSTUR");
        }

        [HttpGet]
        public ActionResult Trips(int? id)
        {
            return GetRelatedDataForParent<Ship>(id, "Trips");
        }

        [HttpGet]
        public override ActionResult Details(int? id, string type)
        {
            return DetailsHandler<TripViewModel>(id, (o) =>
            {
                return new TripViewModel()
                {
                    Id = o.Id,
                    TripId = o.TripId,
                    From = o.From,
                    To = o.To,
                    TripNumber = o.TripNumber,

FMFWebApp/BootstrapWebApplication/Views/Ship/Delete.cshtml
@model BootstrapWebApplication.Models.Ship

@Html.Partial("_DeleteHeaderPartial", new BootstrapCore.Helpers.FormDeleteData() { ViewTitle = @Resources.Ship })
@if (!@Request.IsAjaxRequest())
{
    // display any information to the user before deleting?
}
@Html.Partial("_DeleteFooterPartial", new BootstrapCore.Helpers.FormDeleteData() { Id = @Model.Id })

FMFWebApp/BootstrapWebApplication/Views/Ship/Details.cshtml
@model BootstrapWebApplication.Models.Ship
@*@section SidebarMenu {
        <ul class="nav nav-sidebar">
        <li class="active"><a href="#"></a></li>

        <li><a href="#"></a></li>
    </ul>
    }*@
@{
    var controllerName = ViewContext.GetControllerName();
    var holidayPayFromYear = @DateTime.Now.Year - 6;
    var holidayPayToYear = @DateTime.Now.Year - 1;
}
@if (!@Request.IsAjaxRequest())
{
    ViewBag.Title = @BootstrapResources.Resources.Ship + " " + @Model.Code + " - " + @Model.Name;

}
<div>
    <div class="row">
        <div class="col-md-6">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <strong>@ViewBag.Title</strong>
                        @if (!@Request.IsAjaxRequest())
                        {
                            <span class="pull-right">
                                @Html.Partial("_BackToListPartial", Model)
                            </span>
                        }
                    </h3>
                </div>
                <div class="panel-body">

                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Code)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Code)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Name)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.ShippingCompany)
                        </dt>

                        <dd>
                            @{
                                var scName = @Html.DisplayForHtmlDecoded(model => model.ShippingCompany.EmployerNumber).ToString();
                                scName += " " + @Html.DisplayForHtmlDecoded(model => model.ShippingCompany.Name).ToString();
                            }
                            @Html.ActionLink(scName, "Details", "ShippingCompany", new { @id = Model.ShippingCompanyId }, new { })
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.ContactCompanyName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.ContactCompanyName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.ShipType)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.ShipType.Code) @Html.DisplayFor(model => model.ShipType.Description)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Status)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Status) @ViewBag.StatusText
                        </dd>

                        @*<dt>
                                @Html.DisplayNameFor(model => model.IND_REG)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.IND_REG)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.UD_REG)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.UD_REG)
                            </dd>*@

                    </dl>
                    @if (@Model.PrimaryPhone != null)
                    {
                         @Html.Partial("_PhonePartial", Model.PrimaryPhone);
                    }
                    @if (@Model.PrimaryAddress != null)
                    {
                        @Html.Partial("_AddressPartial", Model.PrimaryAddress);
                    }
                </div>
            </div>

        </div>
        <div class="col-md-6">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><strong>@Resources.Information</strong></h3>
                </div>
                <div class="panel-body">

                    @Html.Action("DetailsCompact", "ChangeEvent", @Model.ChangeEvent)

                    <hr />

                    <div id="tripInfoForYear">
                        <dl class="dl-horizontal">
                            <dt>@Resources.DaysThisYear</dt>
                            <dd>
                                <span id="DayCount"></span>
                                @*<span data-bind="text: DayCount"></span>*@
                            </dd>
                            <dt>@Resources.TripsThisYear</dt>
                            <dd>
                                <span id="TripCount"></span>
                                @*<span data-bind="text: TripCount"></span>*@
                            </dd>
                            <dt>@Resources.Last</dt>
                            <dd>
                                <span id="LastDate"></span>
                                <!-- todo: fix date formatting (moment.js says invalid date!!)-->
                                @*<span data-bind="text: LastDate() ? moment(LastDate()).format('LL') : '@Resources.Empty'"></span>*@
                            </dd>
                        </dl>
                    </div>

                    <hr />

                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Tonnage)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Tonnage)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.HK)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.HK)
                        </dd>
                    </dl>

                    <hr />

                    @*<dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.ShippingCompany.EmployerNumber)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.ShippingCompany.EmployerNumber)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.ALT_ID)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.ALT_ID)
                            </dd>
                        </dl>

                        <hr />*@

                    @Html.Action("LabelInfo", @Model)

                </div>
            </div>

        </div>
    </div>

    @if (!@Request.IsAjaxRequest())
    {
        <ul id="tabs" class="nav nav-tabs" role="tablist">
            @*<li><a href="#signons" role="tab" data-toggle="tab">@Resources.SignOns</a></li>*@
            <li class="active"><a href="#ship-trips" role="tab" data-toggle="tab">@Resources.Trips</a></li>
            <li><a href="#comments" role="tab" data-toggle="tab">@Resources.Comments</a></li>
            <li><a href="#addresses" role="tab" data-toggle="tab">@Resources.Addresses</a></li>
            <li><a href="#phoneNumbers" role="tab" data-toggle="tab">@Resources.Phones</a></li>
            <li><a href="#log" role="tab" data-toggle="tab">@Resources.Log</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active" id="ship-trips">@Html.Action("Trips", "Trip", @Model)</div>
            <div class="tab-pane" id="comments">@Html.Action("Comments", "ShipComment", @Model)</div>
            @*<div class="tab-pane " id="signons">@Html.Action("ShipSignOns", "SignOn", @Model)</div>*@
            <div class="tab-pane" id="addresses">@Html.Action("Addresses", "ShipAddress", @Model)</div>
            <div class="tab-pane" id="phoneNumbers">@Html.Action("Phones", "ShipPhone", @Model)</div>
            <div class="tab-pane" id="log">@Html.Action("Logs", "Log", @Model.Entity)</div>
        </div>

        <script>
            $(function () {

                $.navbarContextMenu("@Resources.Functions <span class='caret'></span>", [
                    "<a href='#' class='edit-action' data-toggle='modal' data-controller-name='Ship' data-action-name='Edit?id=@Model.Id' data-model-name='Ship'>@Resources.Edit</a>"
                ]);

                $(document).on("modalClosed", function (e, d) {
                    setTimeout(function () {
                        //console.log(e); console.log(d);
                        console.log(d.modelName);
                        console.log(d.data);
                        if (d.data != null || d.data != undefined) {
                            if (d.modelName == 'trip') {
                                navigate("/Trip/Details/" + d.data.Id);
                            }
                        }
                        //pvm.load(d.modelName, d.data);
                        @*console.log(@Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model.BankAccounts)));*@
                    }, 1000);

                });

                $('#tabs a').click(function (e) {
                    e.preventDefault();
                    var self = $(this);
                    var id = self.attr('href').replace("#", "");
                    var url = "";
                    var data = null;
                    switch (id) {
                        case "ship-trips":
                            url = '@Url.Action("Trips", "Trip")'; data = { id: '@Model.Id' };
                            break;
                        case "comments":
                            url = '@Url.Action("Comments", "ShipComment")'; data = { id: '@Model.Id' };
                            break;
                        case "addresses":
                            url = '@Url.Action("Addresses", "ShipAddress")'; data = { id: '@Model.Id' };
                            break;
                        case "phoneNumbers":
                            url = '@Url.Action("Phones", "ShipPhone")'; data = { id: '@Model.Id' };
                            break;
                        case "logs":
                            url = '@Url.Action("Logs", "Log")'; data = { id: '@Model.Id' };
                            break;
                    }
                    //alert(id + " " + url);
                    if ($("#" + id).html().trim().length == 0) {
                        $("#" + id).html('<p style="margin-top:50px; text-align:center;"><img src="/Content/kendo/2015.1.408/styles/Uniform/loading-image.gif" /></p>');
                        $.get(url, data, function (html) {
                            $("#" + id).html(html);
                        });
                    }
                    self.tab('show');
                });


                @*$.getDataAsJson('/api/Ship/SignOns', {
            'shipId': '@Model.Id',
            'type': 'json'
        }, function (json) {
            console.log(json.length);
            //pvm.add("SignOns", json);
            //pvm.apply();
        }, function (error) {
            console.log(error);
        });*@



                $.getDataAsJson('/api/Ship/GetTripInfoForYear', {
                    'id': '@Model.Id',
                    //todo: make year dynamic (input)
                    'year': '@DateTime.Now.Year',
                    'type': 'json'
                }, function (json) {
                    //console.log(json);
                    //var mapping = ko.mapping.fromJS([]);
                    //ko.mapping.fromJS(json, mapping);
                    //$('#LastSignOnFromDate').html(moment(json.SignOn.From).format('LL'));
                    $('#DayCount').html(json.DayCount);
                    $('#TripCount').html(json.TripCount);
                    if (json.LastTripDate) {
                        $('#LastDate').html(kendo.toString(new Date(json.LastTripDate), "d"));//moment(json.LastTripDate).format('LL'));
                    }
                    else {
                        $('#LastDate').html("-");
                    }
                }, function (error) {
                    console.log(error);
                });

            });
        </script>
    }
</div>

FMFWebApp/BootstrapWebApplication/Views/Ship/LabelInfo.cshtml
@model BootstrapWebApplication.Models.Ship

<dl class="dl-horizontal">
    <dt>
        @Resources.Label
    </dt>

    <dd>
        @{
            if (Model.ETI_DATO.HasValue)
            {
                @Resources.PrintedOn <strong>@Html.DisplayFor(model => model.ETI_DATO, "DateTime2")</strong>
            }
            if (!String.IsNullOrEmpty(Model.ETI_ID))
            {
                <br />
                @Resources.PrintedBy    <strong>@Html.DisplayFor(model => model.ETI_ID)</strong>
            }
            if (!Model.ETI_DATO.HasValue && String.IsNullOrEmpty(Model.ETI_ID))
            {
                <strong>@Resources.NotYetPrinted</strong>
            }
        }
    </dd>
</dl>

FMFWebApp/BootstrapWebApplication/Views/Ship/LabelReport.cshtml
@model BootstrapWebApplication.Models.ShipLabelReportParameters
@{
    //ViewBag.Title = @Resources.ReportFor + " " + @Resources.Member + " " + @Resources.SignOns;
    Layout = "~/Views/Shared/_LayoutReporting.cshtml";
}
@{
    var canOpenReport = false;
    Boolean.TryParse("" + TempData["CanOpenReport"], out canOpenReport);
    if (canOpenReport)
    {
        @Html.Partial("_ReportHeaderPartial")
        var reportSource = new UriReportSource() { Uri = "p2720.trdx" };
        reportSource.Parameters.Add("ShipCodeFrom", @Request.QueryString["ShipCodeFrom"]);
        reportSource.Parameters.Add("ShipCodeTo", @Request.QueryString["ShipCodeTo"]);
        @Html.Partial("_ReportFooterPartial", reportSource)
    }
}
<script>
    function onPrint() {
        // Optionally implement code to be executed after the print button on the Telerik Report Viewer has been clicked
    }
</script>